### ISSUE TITLE
Erro 'gmx_mpi' is not a typo you can use command-not-found to lookup the package that contains it, like this:     cnf gmx_mpi

### ISSUE THREAD

**Issue by VictorL77** [m3g/XEMMSB2021#1]
Não tenho muita familiaridade com programação e linux, então não sei do que se trata.
Esse erro do título apareceu após testar a instalação com o comando gmx_mpi mdrun -h

**Comment by lmiq** [comment]
Provavelmente a instalação do gromacs e/ou plumed não funcionou, ou falta definir as variáveis de ambiente. Volte no tutorial na parte que fala de `setenv.sh`, e faça ela com cuidado.
