### ISSUE TITLE
/plumed2/lib/libplumed.so: Undefined reference to `plumed_symbol_table_init'

### ISSUE THREAD

**Issue by vfirmino** [m3g/XEMMSB2021#2]
olá

Na instalação do gromacs, no final da execução do comando "make -j 4" aparecem dois erros:

[100%] Linking CXX executable ../../bin/gmx_mpi
/plumed2/lib/libplumed.so: undefined reference to `plumed_symbol_table_init'
/plumed2/lib/libplumed.so: undefined reference to `plumed_symbol_table'
collect2: error: ld returned 1 exit status
src/programs/CMakeFiles/gmx.dir/build.make:105: recipe for target 'bin/gmx_mpi' failed
make[2]: *** [bin/gmx_mpi] Error 1
CMakeFiles/Makefile2:5536: recipe for target 'src/programs/CMakeFiles/gmx.dir/all' failed
make[1]: *** [src/programs/CMakeFiles/gmx.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../../bin/template
/plumed2/lib/libplumed.so: undefined reference to `plumed_symbol_table_init'
/plumed2/lib/libplumed.so: undefined reference to `plumed_symbol_table'
collect2: error: ld returned 1 exit status
share/template/CMakeFiles/template.dir/build.make:85: recipe for target 'bin/template' failed
make[2]: *** [bin/template] Error 1
CMakeFiles/Makefile2:2094: recipe for target 'share/template/CMakeFiles/template.dir/all' failed
make[1]: *** [share/template/CMakeFiles/template.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Alguma ideia do que devo fazer?

**Comment by lmiq** [comment]
Imagino que alguma coisa deu errado com a instalação do plumed, ou com a definição das variáveis de ambiente que fazem com que o make do gromacs enxergue que o plumed está instalado. 

É importante esta parte *antes* de tentar compilar o gromacs:

```
export PATH=$PATH:/$work/plumed2/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$work/plumed2/lib
export PLUMED_KERNEL=$PLUMED_KERNEL:$work/plumed2

```

**Comment by vfirmino** [comment]
Adicionei as variáveis, mas ainda assim não consegui fazer a instalação. 

Pesquisando eu encontrei uma questão do mesmo problema com NAMD aqui: https://github.com/plumed/plumed2/issues/429

Não consegui utilizar a solução sugerida. Mas como foi respondido no link  "_...this is the expected behavior of shared libraries
under Linux when they are installed in nonstandard paths.__".

Então instalei o plumed e o gromacs nos diretórios padrão e não no $work. Os outros programas do tutorial foram instalados no $work. Fiz os testes e parece estar tudo ok.

Obrigado!

**Comment by lmiq** [comment]
Provavelmente o problema está nas variáveis de ambiente, sim, na definição dos diretórios `work` e `repo`. Mas tudo bem, colocar nos diretórios padrão é uma alternativa também.
