### ISSUE TITLE
Awk: line 173: syntax error at or near *

### ISSUE THREAD

**Issue by vfirmino** [m3g/XEMMSB2021#3]
Esse erro aparece no escalonamento das topologias quando uso o comando:

plumed partial_tempering 1.00 < processed.top > ./0/topology.top

Essa é a linha 173 do arquivo processed.top:
CT N*         1    0.14750   282001.6 ; 7,(1986),230; ADE,CYT,GUA,THY,URA

O que pode estar causando isso?

**Comment by lmiq** [comment]
Você está usando Windows? A única coisa que consigo imaginar é que esse caractere `*` está dando algum problema em Windows. Nessa linha mesmo não parece ter nada errado. Se puder, coloque o comando exato que você está dando e a saída exata de tudo o que aparece na tela.

**Comment by vfirmino** [comment]
Estou usando linux. Eu consegui resolver instalando o gawk no meu computador. Eu estava usando o awk, que aparentemente não é utilizado pelo plumed.
