### ISSUE TITLE
Erro na localização dos arquivos (PDB ou script) para rodar o packmol

### ISSUE THREAD

**Issue by Eduardo1ra** [m3g/XEMMSB2021#4]
Olá,

No meu caso, parece que não está encontrando esses scripts ou os arquivos PDB para gerar as caixas nos dois diretórios. 

eduardo@inspiron5480:~/Documents/Cursos/Curso_enovelamento/Simulations/AAQAA_0vv$ packmol < box.inp 

################################################################################

 PACKMOL - Packing optimization for the automated generation of
 starting configurations for molecular dynamics simulations.
 
                           Included as part of Packmol Memgen
                                                              Version 18.169 

################################################################################

  Packmol must be run with: packmol < inputfile.inp 

  Userguide at: www.ime.unicamp.br/~martinez/packmol 

  Reading input file... (Control-C aborts)
  Will print BOX SIDE informations. 
  Will sum    1.0000000000000000       to each side length on print
  Seed for random number generator:        10222
  Output file: system.pdb
  Reading coordinate file: /home/eduardo/Documents/Cursos/Curso_enovelamento/XEMMSB2021/Simulations/julia/../InputData/PDB/AAQAA.pdb
  Reading coordinate file: /home/eduardo/Documents/Cursos/Curso_enovelamento/XEMMSB2021/Simulations/julia/../InputData/PDB/tip4p2005.pdb
  Number of independent structures:            2
  The structures are: 
  Structure            1 :/home/eduardo/Documents/Cursos/Curso_enovelamento/XEMMSB2021/Simulations/julia/../InputData/PDB/AAQAA.pdb(         174  atoms)
  Structure            2 :/home/eduardo/Documents/Cursos/Curso_enovelamento/XEMMSB2021/Simulations/julia/../InputData/PDB/tip4p2005.pdb(           4  atoms)
  Maximum number of GENCAN loops for all molecule packing:          400
  Total number of restrictions:            2
  Distance tolerance:    2.0000000000000000     
  Warning: Type of residue numbering not set for structure            1
At line 852 of file getinp.f90 (unit = 10)
Fortran runtime error: Cannot open file '/home/eduardo/Documents/Cursos/Curso_enovelamento/XEMMSB2021/Simulations/julia/.': Is a directory

Error termination. Backtrace:
#0  0x14ffb2ad82ed in ???
#1  0x14ffb2ad8ed5 in ???
#2  0x14ffb2ad969d in ???
#3  0x14ffb2c4becd in ???
#4  0x14ffb2c4c214 in ???
#5  0x5571fbc41d88 in ???
#6  0x5571fbc49b40 in ???
#7  0x5571fbc578e5 in ???
#8  0x5571fbc2729e in ???
#9  0x14ffb234fbf6 in ???
#10  0x5571fbc272f9 in ???
#11  0xffffffffffffffff in ???

---Seria apenas uma questão de localização dos arquivos?

**Comment by lmiq** [comment]
Você tem que instalar a versão mais recente do Packmol, direto do site, ou como indicado no tutorial. A sua versão é antiga e tem um problema com nomes de arquivos muito longos.
