### ISSUE TITLE
Arquivo .gro da etapa de minimização

### ISSUE THREAD

**Issue by andresamsilva** [m3g/XEMMSB2021#5]
Olá professor. Ao gerar a minimização dos sistemas olhei o arquivo .gro de saída pelo vmd (estou mandando a figura). A aparência seria essa mesmo? Me pareceu um problema de pbc. O mesmo acontece para o sistema de peptídeo em solução de água e TFE.
![minimization](https://user-images.githubusercontent.com/75586512/119733348-c6af4080-be4f-11eb-870b-7547ced1c9f3.jpg)

**Comment by andresamsilva** [comment]
Acho que já identifiquei o problema, é só um problema de visualização certo? Usei o -pbc nojump no trjconv e o peptídeo voltou para o centro da caixa. :D

**Comment by lmiq** [comment]
Isso mesmo.
